### PR TITLE
Truncate logs that exceed GitHub.com's max length

### PR DESCRIPTION
**Pull request by jugglinmike**
GitHub.com enforces a limit on comments' total character count; comments
posted to the API that exceed this limit are rejected. Truncate
overly-long log data prior to submitting to GitHub.com and prefix the
modified comment with a message that explains the modification.

@bobholt I'm not set up for local testing. If it's not too much trouble, could
you verify this change with your fork?

### CODE REVIEW

**Comment by sideshowbarker** [comment]
LGTM but am assuming we want @bobholt to review and sign off

**Comment by bobholt** [comment]
In the process of running a build and checking the output now (I did it wrong the first time).

**Comment by bobholt** [comment]
LGTM. You can see the output here: https://github.com/bobholt/web-platform-tests/pull/12

**Comment by sideshowbarker** [comment]
> You can see the output here: bobholt/web-platform-tests#12

Nice, OK will merge and pull this to w3c-test.org

**Comment by sideshowbarker** [comment]
OK now live at https://w3c-test.org/prbuildbot.py

**Comment by jugglinmike** [comment]
Thanks, Bob and Michael!

**Pull request merged**
